version: '3.8'

services:
  alpha:
    build: .
    container_name: alpha
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - APP_DOMAIN=alpha.zainalmultazam.com
      - TZ=Asia/Jakarta
